language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate
- bundle exec rspec -fd spec
deploy:
  provider: heroku
  api_key:
    secure: MBn8ikadkudP0VZSj1eRg6N9hh/UNW57sFruoEs82JyW8Y45jqTE4p3ySVxY6rRy9ODXib4RQs/tUQMMvKj8OqpR75PRqrB3wdhctqOvx4/ba8CN2+ipEw7NUPx80+Y2zpMW2F4lnfy79FQa9gVAsMDU0sBldfWGWddZ7v5rw0eso4ElIIVtUJjQ+OTBQjbiUy5Uv1/nYdYyIptpsPrwgus2mco2j5RNOH2JpFZcoyim6bfVHBp2mb7aUSAV6w+wsG3vkRe3wSt7r3hrFDxzJHxyBsaQyp+JnFUwyhx+7lgWUitcFH5URHZMSlvML5ICS91CaQE3+Ccp8F1EE/R/IFMlXJT6kzgGrCg7ZBdP5f3Ai91Fm05R93OpNa4CFGtOdfmtpqA6/OsjLMDqa2SB6TlMfourkAfwf5xXlQ3A8lONY0SoPqhZXYpYdvXcqAI/zlaBf6HixJ+WFMAqZnAQjhe02bmJGZ97npOKstw33SOHe61bVj6e31hJl87QCFoSdbWROEzL6RWtWgCgUxs7xjNznKjN/3ANCdVnP899WuyRnvO+PuLwyZ4kAbfMUyF6kO0Lg00Z7iNjDwYBHDEd3VmAex3h6AUirP4oLFicZ6noeVd8lRne7TJO4WxIugMJvSiWSLxrD42BEXlKlE//OqIz64g235B3YC/QBTXdn7s=
  app: paavonkaljasivu
